import type { PersonageConfig } from '@/types'

export const personagesConfig: PersonageConfig[] = [
  {
    slug: 'steve-jobs',
    dir: 'steve-jobs-skill',
    name: 'Steve Jobs（史蒂夫·乔布斯）',
    description: '苹果公司联合创始人，曾任苹果公司 CEO；曾任皮克斯动画董事长兼 CEO',
    avatar: '/avatars/steve-jobs.png',
    tags: ['科技', '商业'],
    born: '1955-02',
    died: '2011-10',
  },
  {
    slug: 'jiajing',
    dir: 'jiajing-perspective-skill',
    name: '1566 嘉靖',
    description:
      '《大明王朝1566》中的嘉靖视角：权力结构、组织博弈与决策困境；基于刘和平原著剧本提炼的思维框架（艺术形象，非历史定论）',
    avatar: '/avatars/jiajing.png',
    tags: ['历史', '权谋', '影视'],
    born: '1507-09',
    died: '1567-01',
  },
  {
    slug: 'feynman',
    dir: 'feynman-skill',
    name: 'Richard Feynman（理查德·费曼）',
    description: '量子电动力学诺奖得主；曼哈顿计划、挑战者号调查参与者',
    avatar: '/avatars/feynman.png',
    tags: ['科学', '教育'],
    born: '1918-05',
    died: '1988-02',
  },
  {
    slug: 'trump',
    dir: 'trump-skill',
    name: 'Donald Trump（唐纳德·特朗普）',
    description: '美国第 45、47 任总统，共和党人；曾为商人、电视制作人',
    avatar: '/avatars/trump.png',
    tags: ['政治', '商业'],
  },
  {
    slug: 'elon-musk',
    dir: 'elon-musk-skill',
    name: 'Elon Musk（埃隆·马斯克）',
    description: '企业家；SpaceX、特斯拉（Tesla）等公司的联合创始人与主要管理者',
    avatar: '/avatars/elonmusk.png',
    tags: ['科技', '商业'],
    born: '1971-06',
  },
  {
    slug: 'zhang-yiming',
    dir: 'zhang-yiming-skill',
    name: '张一鸣',
    description: '字节跳动创始人，曾任 CEO；公司主要产品含今日头条、抖音、TikTok',
    avatar: '/avatars/zhangyiming.png',
    tags: ['科技', '商业'],
    born: '1983-04',
  },
  {
    slug: 'luoyonghao',
    dir: 'luoyonghao-skill',
    name: '罗永浩（Luo Yonghao）',
    description: '锤子科技创始人，前新东方教师，"交个朋友"创始人；"真还传"主角',
    avatar: '/avatars/luoyonghao.png',
    tags: ['商业', '科技'],
    born: '1972',
  },
  {
    slug: 'zhangxuefeng',
    dir: 'zhangxuefeng-skill',
    name: '张雪峰',
    description: '从事考研辅导、高考志愿填报与升学咨询的讲师与媒体人',
    avatar: '/avatars/zhangxuefeng.png',
    tags: ['教育', '商业'],
    born: '1984-05-18',
    died: '2026-03-24',
  },
  {
    slug: 'laozi',
    dir: 'laozi-skill',
    name: '老子（Laozi）',
    description: '道家学派创始人，《道德经》作者；春秋战国时期伟大的哲学家和思想家',
    avatar: '/avatars/laozi.png',
    tags: ['哲学', '文化'],
    born: '约公元前571年',
    died: '约公元前471年',
  },
  {
    slug: 'paul-graham',
    dir: 'paul-graham-skill',
    name: 'Paul Graham（保罗·格雷厄姆）',
    description: 'Y Combinator 联合创始人，创业孵化与科技随笔作者',
    avatar: '/avatars/paul-graham.png',
    tags: ['商业', '科技'],
  },
  {
    slug: 'spongebob',
    dir: 'spongebob-skill',
    name: '海绵宝宝（SpongeBob SquarePants）',
    description: '比基尼堡蟹堡王首席炸蟹堡厨师，全宇宙最乐观的海绵生物',
    avatar: '/avatars/spongebob.png',
    tags: ['动漫', '娱乐'],
    born: '1999-05-01',
  },
]
